system:
  node_id: py_ginlong
  log_level: INFO
  enable_sniffer: false
mqtt:
  broker: 192.168.106.5
  port: 1883
  discovery_prefix: homeassistant
driver:
  type: tcp
  host: 192.168.106.14
  port: 502
  timeout: 1
  inter_frame_delay: 0.37
  connect_timeout: 3
  idle_timeout: 0.11
  max_response_bytes: 2048
  max_frame_time: 1
  flush_max_time: 0.2
devices:
  - uid: 1
    device_type: 6k_inverter
    adapter: solis_inverter
    profile: solis_inverter_map2
    poll_interval: 6
    mode: active
  - uid: 2
    device_type: 6k_inverter
    adapter: solis_inverter
    profile: solis_inverter_map2
    poll_interval: 6
    mode: active
  - uid: 3
    device_type: 6k_inverter
    adapter: solis_inverter
    profile: solis_inverter_map2
    poll_interval: 6
    mode: active
  - uid: 4
    device_type: 6k_inverter
    adapter: solis_inverter
    profile: solis_inverter_map2
    poll_interval: 6
    mode: active